version: "3"

services:
  web:
    build: ./docker/nginx
    ports:
      - 80:80
    depends_on:
      - "app"
  app:
    tty: true
    build: 
      context: ./
      dockerfile: ./docker/go/Dockerfile
    volumes:
      - ./app:/go/src/app
    env_file:
      - ./docker/go/.env
    ports:
      - 3000
    depends_on:
      - "db"
  db:
    build: ./docker/mysql
    ports:
      - 3306:3306
    env_file:
      - ./docker/mysql/.env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.conf:/etc/mysql/my.conf
      - ./docker/mysql/init_sqls:/docker-entrypoint-initdb.d
volumes:
  mysql_data: